In [1]:
import pandas as pd
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from modules.community_detection import community_detection

/home/miriam/Documents/Projects/EchoChamber/.venv/lib/python3.11/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/miriam/Documents/Projects/EchoChamber/.venv/lib/python3.11/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/miriam/Documents/Projects/EchoChamber/.venv/lib/python3.11/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/miriam/Documents/Projects/EchoChamber/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/miriam/Documents/Projects/EchoChamber/.venv/lib/python3.11/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

In [3]:
raw_data = pd.read_csv('./data/vaccination2.csv')

In [4]:
communities = community_detection("./data/", "vax", comType="weightComm")

Name: Final vax Direct Graph
Type: DiGraph
Number of nodes: 39604
Number of edges: 95126
Average in degree:   2.4019
Average out degree:   2.4019

In [6]:
with open("communities.txt", "w") as f:
    f.write(str(communities))

In [49]:
df = raw_data.copy()
df = df[["username", "tweet"]]
df.head()

          username                                              tweet
0  peaceahappiness   Thinks:  ... tetanus vaccination currently? ...😉
1  briannacelegill  Forced Vaccination & It's Ties To Eugenics - D...
2       dawnpike20  We have had our flu vaccination to protect our...
3       plasticdoe  That's true, they are not, which is why there ...
4          wv_dhhr  Flu vaccination during pregnancy is safe, help...

In [50]:
df_com0 = df[df['username'].isin(communities[0])]
df_com1 = df[df['username'].isin(communities[1])]

In [51]:
def bert_topic(docs):
    ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)
    topic_model = BERTopic(ctfidf_model=ctfidf_model)
    topics, probs = topic_model.fit_transform(docs)
    return topic_model

In [52]:
docs = df_com0.tweet.to_list()
com0 = bert_topic(docs)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [53]:
com0.save("com0", serialization="safetensors", save_ctfidf=True)

In [55]:
com0.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5904,-1_antivaccination_kids_think_parents,"[antivaccination, kids, think, parents, etc, l...",[Vaccination rates stalled globally at 86% (lo...
1,0,1055,0_boys_hpv_cervical_cancers,"[boys, hpv, cervical, cancers, cervicalcancer,...",[We knew the HPV vaccination was effective... ...
2,1,732,1_badger_badgers_derbyshire_cull,"[badger, badgers, derbyshire, cull, culling, b...",[#WednesdayMotivation Avon #Wildlife Trust aim...
3,2,725,2_flu_influenza_season_staff,"[flu, influenza, season, staff, winter, flufig...",[Today is the launch of our staff flu vaccinat...
4,3,665,3_rabies_dogs_worldrabiesday_dog,"[rabies, dogs, worldrabiesday, dog, endrabiesn...",[FREE RABIES VACCINATION CLINIC FOR PETS! Reg...
...,...,...,...,...,...
239,238,10,238_thier_grows_hamful_everycom,"[thier, grows, hamful, everycom, respective, c...",[Must say all parents must provide proper vacc...
240,239,10,239_minus_ring_transporting_stored,"[minus, ring, transporting, stored, centigrade...","[""Ring vaccination is a new and vital tool in ..."
241,240,10,240_evee_httpswwwtheguardiancomsociety2019jul1...,"[evee, httpswwwtheguardiancomsociety2019jul10v...","[""I just want the truth out there: Babies asph..."
242,241,10,241_educatebeforeyouvaccinate_httpsvaccinatein...,"[educatebeforeyouvaccinate, httpsvaccinateindi...",[Who does need #vaccination ? #vaccineswork ...
243,242,10,242_pictwittercomgrj3mfbgh7_pictwittercommxe4j...,"[pictwittercomgrj3mfbgh7, pictwittercommxe4jce...","[Nice job, critics of vaccination; nice job; h..."

In [3]:
com0 = BERTopic.load("com0")
com1 = BERTopic.load("com1")

In [4]:
com0.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5904,-1_antivaccination_kids_think_parents,"[antivaccination, kids, think, parents, etc, l...",NaN
1,0,1055,0_boys_hpv_cervical_cancers,"[boys, hpv, cervical, cancers, cervicalcancer,...",NaN
2,1,732,1_badger_badgers_derbyshire_cull,"[badger, badgers, derbyshire, cull, culling, b...",NaN
3,2,725,2_flu_influenza_season_staff,"[flu, influenza, season, staff, winter, flufig...",NaN
4,3,665,3_rabies_dogs_worldrabiesday_dog,"[rabies, dogs, worldrabiesday, dog, endrabiesn...",NaN
...,...,...,...,...,...
239,238,10,238_thier_grows_hamful_everycom,"[thier, grows, hamful, everycom, respective, c...",NaN
240,239,10,239_minus_ring_transporting_stored,"[minus, ring, transporting, stored, centigrade...",NaN
241,240,10,240_evee_httpswwwtheguardiancomsociety2019jul1...,"[evee, httpswwwtheguardiancomsociety2019jul10v...",NaN
242,241,10,241_educatebeforeyouvaccinate_httpsvaccinatein...,"[educatebeforeyouvaccinate, httpsvaccinateindi...",NaN
243,242,10,242_pictwittercomgrj3mfbgh7_pictwittercommxe4j...,"[pictwittercomgrj3mfbgh7, pictwittercommxe4jce...",NaN

In [54]:
com1.get_document_info(docs)

NameError: name 'topic_model' is not defined